name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: check cache
        uses: actions/cache/restore@v3
        id: cache-check
        with:
          path: ${{ github.workspace }}/*
          key: "cache-${{ github.sha }}"
          lookup-only: true
          restore-keys: "cache-"
          
      - name: save cache
        uses: actions/cache/save@v3
        if: ${{ !steps.cache-check.cache-hit }}
        with:
          path:  ${{ github.workspace }}/*
          key: "cache-${{ github.sha }}"
          
  restore-cache:
    runs-on: ubuntu-latest
    needs: [create-cache]
    steps:
      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/*
          key: "cache-${{ github.sha }}"
          # Cache should not miss.
          fail-on-cache-miss: true
          restore-keys: "cache-"
