name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: check cache
        uses: actions/cache@v3.2.4
        id: cache-check
        with:
          path: ${{ github.workspace }}/*
          key: 'cache-${{ github.sha }}'
          
  restore-cache:
    runs-on: ubuntu-latest
    steps:
      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/*
          key: "cache-${{ github.sha }}"
          restore-keys: "cache-"
